// Euler2.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include <iostream>
#include <vector>
using namespace std;

bool isEven(int x) {
	if (x % 2 == 0) {
		return false;
	}
	return true;
}

int main()
{
	// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
	// By starting with 1 and 2, the first 10 terms will be :
	// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
	// find the sum of the even - valued terms.

	vector<int> seq;
	seq.push_back(1);
	seq.push_back(2);

	int lastNum = seq.rbegin()[0] + seq.rbegin()[1];

	while (lastNum < 4000000) {
		seq.push_back(lastNum);
		lastNum = seq.rbegin()[0] + seq.rbegin()[1];
	}

	int sum = 0;

	for (int i: seq) {
		if (isEven(i)) {
			sum = sum + i;
		}
	}

	cout << sum << endl;

    return 0;
}

