//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public book()
        {
            this.rentals = new HashSet<rental>();
            this.Wishlists = new HashSet<Wishlist>();
            this.bookreviews = new HashSet<bookreview>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public int copies { get; set; }
    
        public virtual ICollection<rental> rentals { get; set; }
        public virtual ICollection<Wishlist> Wishlists { get; set; }
        public virtual ICollection<bookreview> bookreviews { get; set; }
    }
}
