//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Periwinkle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int Id { get; set; }
        public Nullable<int> Book_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<System.DateTime> Sign_Out_Date { get; set; }
        public Nullable<System.DateTime> Return_Date { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
