//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Periwinkle.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public User()
        {
            this.Rentals = new HashSet<Rental>();
            this.Reviews = new HashSet<Review>();
            this.Wishlists = new HashSet<Wishlist>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name ="First Name")]
        [RegularExpression(@"^[a-zA-Z]+",ErrorMessage = "Needs to be a letter")]
        public string First_Name { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Last Name")]
        [RegularExpression(@"^[a-zA-Z]+", ErrorMessage = "Needs to be a letter")]
        public string Last_Name { get; set; }

        [Required(ErrorMessage = "Required")]
        [EmailAddress(ErrorMessage = "Invalid email address")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Pass")]
        [StringLength(50, ErrorMessage = "Must be between 5 and 20 characters", MinimumLength = 5)]
        public string Pass_Hash { get; set; }
        public string Privilege { get; set; }
    
        public virtual ICollection<Rental> Rentals { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<Wishlist> Wishlists { get; set; }
    }
}
